const canvas=document.getElementById('teardownCanvas');const ctx=canvas.getContext('2d');const slider=document.getElementById('explodeSlider');const loadSlider=document.getElementById('loadSlider');const thermalBtn=document.getElementById('thermalBtn');const labels=document.getElementById('componentLabels');let explode=64,load=58,thermal=true,angle=18,drag=false,lastX=0;
const parts=[
{name:'Outer Frame',short:'FRAME',cost:42,material:'Aluminium alloy',score:'8.9 / 10',thermal:'Low',color:'#91a2ab',x:0,y:-190,w:250,h:22,z:0,desc:'Machined alloy chassis provides structural rigidity and acts as a secondary heat spreader.'},
{name:'Display Assembly',short:'DISPLAY',cost:78,material:'OLED / glass',score:'9.2 / 10',thermal:'Low',color:'#4d7180',x:0,y:-120,w:215,h:95,z:1,desc:'High-density OLED stack bonded to a rigid carrier plate with perimeter adhesive.'},
{name:'Battery Pack',short:'BATTERY',cost:31,material:'Lithium-ion polymer',score:'8.1 / 10',thermal:'Medium',color:'#a38a58',x:-78,y:20,w:105,h:150,z:2,desc:'High-density pouch cell with pull tabs and a protective composite enclosure.'},
{name:'Vapor Chamber',short:'COOLING',cost:18,material:'Copper',score:'9.0 / 10',thermal:'High',color:'#a16a52',x:74,y:20,w:90,h:145,z:3,desc:'Ultra-thin copper vapor chamber distributes processor heat across the mid-frame.'},
{name:'Mainboard',short:'MAINBOARD',cost:86,material:'FR-4 / copper',score:'9.1 / 10',thermal:'High',color:'#355f55',x:0,y:15,w:155,h:115,z:4,desc:'Dense multi-layer board carrying power management, compute, memory and connectivity.'},
{name:'Application Processor',short:'SoC',cost:59,material:'Silicon / copper',score:'9.6 / 10',thermal:'High',color:'#456f77',x:0,y:5,w:52,h:42,z:5,desc:'Dense package design prioritizes compute density. Copper heat spreader sits directly above the package.'},
{name:'Camera Cluster',short:'CAMERA',cost:44,material:'Glass / aluminium',score:'9.0 / 10',thermal:'Medium',color:'#52617a',x:72,y:-12,w:55,h:65,z:6,desc:'Triple-camera module with stabilized optics and compact actuator assemblies.'},
{name:'Speaker / Haptics',short:'I/O',cost:14,material:'Polymer / steel',score:'8.5 / 10',thermal:'Low',color:'#6e6b58',x:-72,y:112,w:48,h:35,z:7,desc:'Compact acoustic and haptic module connected through flex interfaces.'}
];
let selected=parts[5];
function resize(){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}window.addEventListener('resize',resize);
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2+10);ctx.rotate(angle*Math.PI/180*.02);const scale=Math.min(w/480,h/480);ctx.scale(scale,scale);parts.forEach((p,i)=>drawPart(p,i));ctx.restore();updateLabels()}
function drawPart(p,i){const spread=explode/100;const sx=(p.x)*(1+spread*.7),sy=p.y+(p.y<0?-1:1)*spread*105*(p.z/7+.15);ctx.save();ctx.translate(sx,sy);ctx.rotate((p.z-3)*.015);const hot=Math.min(1,Math.max(0,(load-25)/75)*(p.thermal==='High'?1:.55));ctx.shadowBlur=thermal?18*hot:0;ctx.shadowColor=hot>.2?'#ff725c':'#4de7ff';ctx.fillStyle=thermal&&hot>.08?mix(p.color,'#ff543e',hot*.7):p.color;ctx.strokeStyle=i===parts.indexOf(selected)?'#4de7ff':'#45616a';ctx.lineWidth=2;roundRect(-p.w/2,-p.h/2,p.w,p.h,7);ctx.fill();ctx.stroke();ctx.shadowBlur=0;if(p.name==='Mainboard'){ctx.strokeStyle='#8ed7a9';ctx.lineWidth=1;for(let x=-55;x<55;x+=14){ctx.beginPath();ctx.moveTo(x,-42);ctx.lineTo(x+18,42);ctx.stroke()}}if(p.name==='Application Processor'){ctx.fillStyle='#10191e';ctx.fillRect(-17,-13,34,26);ctx.strokeStyle='#9eeaf2';ctx.strokeRect(-17,-13,34,26)}ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function mix(a,b,t){const A=a.match(/\w\w/g),B=b.match(/\w\w/g);if(!A||!B)return a;return '#'+A.map((v,i)=>Math.round(parseInt(v,16)*(1-t)+parseInt(B[i],16)*t).toString(16).padStart(2,'0')).join('')}
function updateLabels(){labels.innerHTML='';parts.filter(p=>p.z>=3).forEach(p=>{const e=document.createElement('div');e.className='component-label';e.textContent=p.short;const spread=explode/100;e.style.left=`calc(50% + ${p.x*(1+spread*.7)*Math.min(canvas.clientWidth/480,canvas.clientHeight/480)}px)`;e.style.top=`calc(50% + ${(p.y+(p.y<0?-1:1)*spread*105*(p.z/7+.15))*Math.min(canvas.clientWidth/480,canvas.clientHeight/480)+10}px)`;e.onclick=()=>select(p);e.style.pointerEvents='auto';labels.appendChild(e)})}
function select(p){selected=p;document.getElementById('componentTitle').textContent=p.name;document.getElementById('componentSubtitle').textContent=p.name==='Application Processor'?'8-core mobile SoC':'Precision engineered module';document.getElementById('componentVendor').textContent=p.name==='Application Processor'?'Astra Semiconductor':'Astra Components Group';document.getElementById('componentCost').textContent='$'+p.cost;document.getElementById('componentMaterial').textContent=p.material;document.getElementById('componentPerformance').textContent=p.score;const t=document.getElementById('componentThermal');t.textContent=p.thermal;t.className=p.thermal==='High'?'thermal-hot':p.thermal==='Low'?'thermal-good':'';document.getElementById('componentNotes').textContent=p.desc;renderBars();draw()}
function renderBars(){const b=document.getElementById('loadBars');b.innerHTML='';for(let i=0;i<18;i++){const e=document.createElement('i');e.className='bar';e.style.height=(20+Math.max(0,Math.sin(i*.7)*25)+load*.45+(selected.thermal==='High'?12:0))+'%';b.appendChild(e)}document.getElementById('loadValue').textContent=Math.round(load*1.15)+'%'}
slider.addEventListener('input',e=>{explode=+e.target.value;document.getElementById('explodeValue').textContent=String(explode).padStart(2,'0')+'%';document.getElementById('explodeLabel').textContent=explode+'%';draw()});loadSlider.addEventListener('input',e=>{load=+e.target.value;document.getElementById('dialCore').textContent=load;const temp=Math.round(30+load*.29);document.getElementById('simTemp').textContent=temp+'°C';document.getElementById('headroomValue').textContent=Math.max(4,100-load)+'%';document.getElementById('headroomBar').style.width=Math.max(4,100-load)+'%';const state=document.getElementById('simulationState');state.textContent=load>82?'CRITICAL':load>65?'HIGH LOAD':'BALANCED';state.className='tiny-tag '+(load>82?'thermal-hot':'');renderBars();draw()});thermalBtn.addEventListener('click',()=>{thermal=!thermal;thermalBtn.classList.toggle('active',thermal);draw()});document.getElementById('resetBtn').addEventListener('click',()=>{explode=64;load=58;slider.value=64;loadSlider.value=58;angle=18;document.getElementById('explodeValue').textContent='64%';document.getElementById('explodeLabel').textContent='64%';document.getElementById('angleValue').textContent='018°';document.getElementById('dialCore').textContent='58';document.getElementById('simTemp').textContent='47°C';renderBars();draw()});canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;angle+=(e.clientX-lastX)*.7;lastX=e.clientX;document.getElementById('angleValue').textContent=(Math.round((angle%360+360)%360)).toString().padStart(3,'0')+'°';draw()});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);renderBars();resize();select(selected);
