const $=id=>document.getElementById(id);
const fileInput=$('fileInput'),uploadBtn=$('uploadBtn'),demoBtn=$('demoBtn'),analyzeBtn=$('analyzeBtn');
const preview=$('previewImage'),dropZone=$('dropZone'),emptyState=$('emptyState'),overlay=$('scanOverlay'),removeBtn=$('removeBtn');
const ingredients=$('ingredients'),count=$('ingredientCount'),verdictCard=$('verdictCard'),confidenceRing=$('confidenceRing'),toast=$('toast');
const verdictKicker=$('verdictKicker'),verdictTitle=$('verdictTitle'),verdictText=$('verdictText'),verdictIcon=$('verdictIcon');
const confidenceValue=$('confidenceValue'),confidenceTitle=$('confidenceTitle'),confidenceText=$('confidenceText'),analysisNote=$('analysisNote');
const historyDialog=$('historyDialog'),historyBody=$('historyBody'),historyClose=$('historyClose'),clearHistoryBtn=$('clearHistoryBtn');
const stateChip=$('analysisChip'),finalStatus=$('finalStatus'),finalHint=$('finalHint'),inputState=$('inputState'),visionConfidence=$('visionConfidence');
const goodCount=$('goodCount'),warnCount=$('warnCount'),badCount=$('badCount');
const state={status:'idle',file:null,objectUrl:null,demo:false,timer:null};

const demoData=[
{name:'حبوب كاملة',status:'good',label:'متوافق'},
{name:'سكر',status:'good',label:'متوافق'},
{name:'زيت نباتي',status:'good',label:'متوافق'},
{name:'نكهة طبيعية',status:'warn',label:'تحتاج تحقق'}
];

function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}
function setStatus(status){state.status=status;dropZone.dataset.status=status;overlay.classList.toggle('active',status==='analyzing');analyzeBtn.disabled=!(status==='ready'||status==='result');removeBtn.disabled=status==='analyzing';const map={idle:'WAITING',ready:'READY',analyzing:'SCANNING',result:'ANALYZED'};if(inputState)inputState.textContent=map[status]||status.toUpperCase();if(stateChip){stateChip.className='state-chip '+(status==='result'?'safe':'');stateChip.textContent=status==='result'?'COMPLETE':status==='analyzing'?'SCANNING':status==='ready'?'READY':'STANDBY'}if(visionConfidence)visionConfidence.textContent=status==='result'?'95%':status==='analyzing'?'…':'95%'}
function setPreview(src){preview.src=src;preview.classList.add('visible');dropZone.classList.add('has-image');emptyState.setAttribute('aria-hidden','true')}
function clearPreview(){if(state.objectUrl){URL.revokeObjectURL(state.objectUrl);state.objectUrl=null}preview.removeAttribute('src');preview.classList.remove('visible');dropZone.classList.remove('has-image');emptyState.removeAttribute('aria-hidden');fileInput.value='';state.file=null;state.demo=false;setStatus('idle')}
function validateFile(file){if(!file)return 'لم يتم اختيار صورة';if(!file.type.startsWith('image/'))return 'الملف المختار ليس صورة';if(file.size>10*1024*1024)return 'حجم الصورة يتجاوز 10MB';return ''}
function loadImage(file){const error=validateFile(file);if(error){showToast(error);return}if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);state.file=file;state.demo=false;state.objectUrl=URL.createObjectURL(file);setPreview(state.objectUrl);setStatus('ready');showToast('تم تجهيز الصورة للتحليل')}
function setVerdict(type,kicker,title,text,confidence){verdictCard.className=`analysis-summary ${type}`;verdictKicker.textContent=kicker;verdictTitle.textContent=title;verdictText.textContent=text;verdictIcon.textContent=type==='safe'?'✓':type==='bad'?'×':type==='warn'?'!':'◌';const deg=Math.round(confidence*360),accent=type==='safe'?'var(--green)':type==='bad'?'var(--red)':'var(--cyan)';confidenceRing.style.background=`conic-gradient(${accent} ${deg}deg,rgba(100,231,238,.12) ${deg}deg)`;confidenceValue.textContent=confidence.toFixed(2);confidenceTitle.textContent=confidence>.9?'ثقة مرتفعة':confidence>.75?'ثقة جيدة':'ثقة منخفضة';confidenceText.textContent='درجة الثقة تقديرية في هذه النسخة التجريبية وليست حكمًا شرعيًا.';if(stateChip){stateChip.className=`state-chip ${type}`;stateChip.textContent=type==='safe'?'HALAL':type==='bad'?'FLAGGED':'VERIFY'}if(finalStatus){finalStatus.textContent=type==='safe'?'الحالة: حلال':type==='bad'?'الحالة: مرفوض':'الحالة: يحتاج تحقق';finalStatus.style.color=type==='safe'?'var(--green)':type==='bad'?'var(--red)':'var(--gold)'}if(finalHint)finalHint.textContent=type==='safe'?'نتيجة تجريبية — راجع المصدر عند الشك':'هناك عنصر يحتاج مراجعة قبل الاعتماد'}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function renderIngredients(data){ingredients.innerHTML=data.length?data.map(x=>`<div class="ingredient ${x.status}"><i></i><b>${escapeHtml(x.name)}</b><span>${escapeHtml(x.label)}</span></div>`).join(''):'<div class="empty-item">لا توجد بيانات بعد</div>';count.textContent=data.length;goodCount.textContent=String(data.filter(x=>x.status==='good').length).padStart(2,'0');warnCount.textContent=String(data.filter(x=>x.status==='warn').length).padStart(2,'0');badCount.textContent=String(data.filter(x=>x.status==='bad').length).padStart(2,'0')}
function saveHistory(result){try{const items=JSON.parse(localStorage.getItem('halallens-history')||'[]');items.unshift({...result,at:new Date().toISOString()});localStorage.setItem('halallens-history',JSON.stringify(items.slice(0,8)))}catch(_){}}
function getHistory(){try{return JSON.parse(localStorage.getItem('halallens-history')||'[]')}catch(_){return[]}}
function formatDate(value){try{return new Intl.DateTimeFormat('ar-DZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch(_){return value}}
function renderHistory(){const items=getHistory();if(!items.length){historyBody.innerHTML='<div class="history-empty">لا توجد تحليلات محفوظة بعد.<br>أجرِ أول تحليل ليظهر هنا.</div>';return}historyBody.innerHTML=items.map(item=>`<div class="history-item"><div><b>${escapeHtml(item.title||'نتيجة')}</b><small>${escapeHtml(formatDate(item.at))}</small></div><strong>${Number(item.confidence||0).toFixed(2)}</strong><span>${item.count||0} عناصر</span></div>`).join('')}
function showHistory(){renderHistory();if(typeof historyDialog.showModal==='function')historyDialog.showModal();else showToast('السجل غير مدعوم في هذا المتصفح')}
function finishAnalysis(){renderIngredients(demoData);setVerdict('safe','نتيجة تجريبية','الحالة: حلال','لم تظهر مكونات مصنفة كمشبوهة في هذا السيناريو التجريبي. تحقق من المصدر عند وجود أي شك.',.95);analysisNote.innerHTML='<b>تنبيه:</b> هذه نتيجة Demo للواجهة. التحليل الحقيقي يحتاج OCR وقاعدة مكونات ومصادر موثوقة ومراجعة منهجية.';saveHistory({title:'الحالة: حلال',confidence:.95,count:demoData.length});setStatus('result');showToast('اكتمل التحليل التجريبي')}
function runAnalysis(){if(state.status==='analyzing')return;if(!(state.status==='ready'||state.status==='result')){showToast('ارفع صورة أولًا');return}setStatus('analyzing');clearTimeout(state.timer);state.timer=setTimeout(finishAnalysis,1250)}
function makeDemoSvg(){return `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="700"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#f2f8b8"/><stop offset="1" stop-color="#c7df70"/></linearGradient></defs><rect width="100%" height="100%" fill="#10282b"/><rect x="250" y="55" width="400" height="590" rx="28" fill="url(#g)"/><rect x="286" y="98" width="328" height="70" rx="12" fill="#ffffff55"/><text x="450" y="145" text-anchor="middle" font-family="Arial" font-size="48" font-weight="700" fill="#173a32">Choco Crunch</text><circle cx="450" cy="372" r="92" fill="#86552e"/><circle cx="414" cy="348" r="11" fill="#ecd28e"/><circle cx="475" cy="406" r="13" fill="#ecd28e"/><text x="450" y="560" text-anchor="middle" font-family="Arial" font-size="18" fill="#173a32">WHOLEGRAIN • SUGAR • VEGETABLE OIL</text></svg>`}
function demo(){clearTimeout(state.timer);state.demo=true;state.file=null;if(state.objectUrl){URL.revokeObjectURL(state.objectUrl);state.objectUrl=null}setPreview('data:image/svg+xml;charset=utf-8,'+encodeURIComponent(makeDemoSvg()));setStatus('ready');showToast('تم تحميل منتج تجريبي');runAnalysis()}

uploadBtn.addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',e=>loadImage(e.target.files?.[0]));analyzeBtn.addEventListener('click',runAnalysis);demoBtn.addEventListener('click',demo);
removeBtn.addEventListener('click',()=>{clearTimeout(state.timer);clearPreview();renderIngredients([]);setVerdict('pending','بانتظار الصورة','جاهز للتحليل','ارفع صورة المنتج لبدء نظام الرؤية والتحليل.',0);analysisNote.innerHTML='<b>ملاحظة:</b> ستظهر تفاصيل التحليل بعد رفع صورة وتشغيل الفحص.';showToast('تمت إزالة الصورة')});
$('helpBtn').addEventListener('click',()=>showToast('ارفع صورة واضحة للمكونات ثم شغّل التحليل'));$('historyBtn').addEventListener('click',showHistory);historyClose?.addEventListener('click',()=>historyDialog.close());clearHistoryBtn?.addEventListener('click',()=>{localStorage.removeItem('halallens-history');renderHistory();showToast('تم مسح السجل')});historyDialog?.addEventListener('click',e=>{if(e.target===historyDialog)historyDialog.close()});
dropZone.addEventListener('dragover',e=>{e.preventDefault();dropZone.classList.add('dragging')});dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('dragging'));dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.classList.remove('dragging');loadImage(e.dataTransfer.files?.[0])});
document.addEventListener('paste',e=>{const file=[...(e.clipboardData?.items||[])].map(x=>x.getAsFile?.()).find(Boolean);if(file){loadImage(file);showToast('تم لصق الصورة من الحافظة')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&historyDialog?.open)historyDialog.close();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();fileInput.click()}});window.addEventListener('beforeunload',()=>{if(state.objectUrl)URL.revokeObjectURL(state.objectUrl)});setInterval(()=>{const el=$('systemTime');if(el)el.textContent=new Date().toLocaleTimeString('en-GB')},1000);
renderIngredients([]);setVerdict('pending','بانتظار الصورة','جاهز للتحليل','ارفع صورة المنتج لبدء نظام الرؤية والتحليل.',0);setStatus('idle');
