const fileInput=document.getElementById('fileInput');const uploadBtn=document.getElementById('uploadBtn');const demoBtn=document.getElementById('demoBtn');const analyzeBtn=document.getElementById('analyzeBtn');const preview=document.getElementById('previewImage');const dropZone=document.getElementById('dropZone');const emptyState=document.getElementById('emptyState');const overlay=document.getElementById('scanOverlay');const removeBtn=document.getElementById('removeBtn');const ingredients=document.getElementById('ingredients');const count=document.getElementById('ingredientCount');const verdictCard=document.getElementById('verdictCard');const confidenceRing=document.getElementById('confidenceRing');const toast=document.getElementById('toast');let hasImage=false;
const demoData=[{name:'مستحلب E120 (قرمزي)',status:'bad',label:'غير حلال / يحتاج تحقق'},{name:'سكر',status:'good',label:'مقبول'},{name:'حبوب كاملة',status:'good',label:'مقبول'},{name:'نكهة طبيعية',status:'warn',label:'تحتاج مصدرًا'},{name:'زيت نباتي',status:'good',label:'مقبول'}];
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove('show'),2400)}
function loadImage(file){if(!file||!file.type.startsWith('image/'))return showToast('اختر ملف صورة صالحًا');if(file.size>10*1024*1024)return showToast('حجم الصورة يتجاوز 10MB');const reader=new FileReader();reader.onload=e=>{preview.src=e.target.result;preview.onload=()=>{preview.classList.add('visible');dropZone.classList.add('has-image');emptyState.style.opacity='.08';analyzeBtn.disabled=false;hasImage=true;showToast('تم تجهيز الصورة للتحليل')};};reader.readAsDataURL(file)}
function resetImage(){hasImage=false;preview.src='';preview.classList.remove('visible');dropZone.classList.remove('has-image');emptyState.style.opacity='1';analyzeBtn.disabled=true;overlay.classList.remove('active')}
function setVerdict(type,kicker,title,text,confidence){verdictCard.className='verdict-card '+type;document.getElementById('verdictKicker').textContent=kicker;document.getElementById('verdictTitle').textContent=title;document.getElementById('verdictText').textContent=text;document.getElementById('verdictIcon').textContent=type==='safe'?'✓':type==='bad'?'×':type==='warn'?'!':'◌';const deg=Math.round(confidence*360);confidenceRing.style.background=`conic-gradient(${type==='safe'?'var(--green)':type==='bad'?'var(--red)':'var(--cyan)'} ${deg}deg,rgba(100,231,238,.12) ${deg}deg)`;document.getElementById('confidenceValue').textContent=confidence.toFixed(2);document.getElementById('confidenceTitle').textContent=confidence>.9?'ثقة مرتفعة':confidence>.75?'ثقة جيدة':'ثقة منخفضة';document.getElementById('confidenceText').textContent='الدرجة مبنية على وضوح النص والمطابقة مع قاعدة المكونات الحالية.'}
function renderIngredients(data){ingredients.innerHTML=data.map(x=>`<div class="ingredient ${x.status}"><i></i><b>${x.name}</b><span>${x.label}</span></div>`).join('');count.textContent=data.length}
function runAnalysis(){if(!hasImage)return showToast('ارفع صورة أولًا');overlay.classList.add('active');analyzeBtn.disabled=true;setTimeout(()=>{overlay.classList.remove('active');renderIngredients(demoData);setVerdict('warn','نتيجة أولية','غير محسوم — يحتاج تحقق','تم العثور على مكوّن مصنّف عالي الحساسية. راجع مصدر E120 قبل اعتماد المنتج.',.95);document.getElementById('analysisNote').innerHTML='<b>ملاحظة:</b> النتيجة هنا محاكاة للواجهة. التحليل الحقيقي يحتاج OCR وقاعدة بيانات موثوقة للمكونات ومصادرها.';analyzeBtn.disabled=false;showToast('اكتمل التحليل التجريبي')},1500)}
function demo(){hasImage=true;dropZone.classList.add('has-image');emptyState.style.opacity='.08';analyzeBtn.disabled=false;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="700"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#edf6a8"/><stop offset="1" stop-color="#cde771"/></linearGradient></defs><rect width="100%" height="100%" fill="#10282b"/><rect x="250" y="60" width="400" height="580" rx="24" fill="url(#g)"/><text x="450" y="180" text-anchor="middle" font-family="Arial" font-size="60" font-weight="700" fill="#173a32">Choco</text><text x="450" y="250" text-anchor="middle" font-family="Arial" font-size="40" fill="#173a32">Crunch</text><circle cx="450" cy="390" r="90" fill="#8c5930"/><circle cx="420" cy="365" r="12" fill="#e8c58b"/><circle cx="476" cy="410" r="13" fill="#e8c58b"/><text x="450" y="560" text-anchor="middle" font-family="Arial" font-size="22" fill="#173a32">INGREDIENTS • E120 • SUGAR • OIL</text></svg>`;preview.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);preview.onload=()=>{preview.classList.add('visible');runAnalysis()};showToast('تم تحميل منتج تجريبي')}
uploadBtn.onclick=()=>fileInput.click();fileInput.onchange=e=>loadImage(e.target.files[0]);removeBtn.onclick=resetImage;analyzeBtn.onclick=runAnalysis;demoBtn.onclick=demo;dropZone.addEventListener('dragover',e=>{e.preventDefault();dropZone.style.borderColor='var(--cyan)'});dropZone.addEventListener('dragleave',()=>dropZone.style.borderColor='');dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.style.borderColor='';loadImage(e.dataTransfer.files[0])});document.getElementById('helpBtn').onclick=()=>showToast('ارفع صورة للمكونات ثم اضغط ابدأ التحليل');document.getElementById('historyBtn').onclick=()=>showToast('السجل سيُضاف مع قاعدة البيانات في المرحلة التالية');
